<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update Comment' => 'Modification d\'un commentaire',
    'Account' => 'Compte',
    'Are you sure you want to delete this item?' => 'Etes-vous sur de vouloir supprimer cet element ?',
    'Comment' => 'Commentaire',
    'Comments Management' => 'Administration des commentaires',
    'Create' => 'Creer',
    'Create User' => 'Creer utilisateur',
    'Delete' => 'Supprimer',
    'Displayed Name' => 'Nom d\'affichage',
    'Email' => 'Email',
    'Home' => 'Accueil',
    'Image' => 'Image',
    'Login' => 'Connexion',
    'Logout' => 'Deconnexion',
    'Password' => 'Mot de passe',
    'Please contact us if you think this is a server error. Thank you.' => 'Merci de nous contacter si vous penser qu\'il s\'agit d\'une erreur serveur. Merci.',
    'Please fill out the following fields to login:' => 'Veuillez remplir les champs suivants pour vous connecter :',
    'Posts Management' => 'Administration des posts',
    'Role' => 'Role',
    'The above error occurred while the Web server was processing your request.' => 'Cette erreur est apparue lorsque le serveur a traite votre reauete',
    'Title' => 'Titre',
    'Update' => 'Modifier',
    'Update Post' => 'Modification d\'un post',
    'Update User' => 'Modification d\'un utilisateur',
    'User' => 'Utilisateur',
    'Username' => 'Nom de connexion',
    'Users Management' => 'Administration d\'utilisateurs',
    'Welcome friend!' => 'Bonjour l\'ami !',
    'You can now access to some fucking amazing features !' => 'Tu peux acceder a tous pleins de fonctionnalites fabuleuses !',
];
