<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'spreaded your post' => 'a tartine votre post',
    'commented on your post' => 'a commente votre post',
    'commented on a post you commented before' => 'a commente un post que vous avez commente',
    'Accept' => 'Valider',
    'Admin' => 'Admin',
    'Are you sure you want to delete this item?' => 'Etes-vous sur de vouloir supprimer cet element ?',
    'Comment' => 'Commenter',
    'Comments' => 'Commentaires',
    'Create' => 'Creer',
    'Create Post' => 'Creer un post',
    'Created By' => 'Creer par',
    'Date' => 'Date',
    'Delete' => 'Supprimer',
    'Displayed name' => 'Nom d\'affichage',
    'Email' => 'Email',
    'Home' => 'Accueil',
    'If you forgot your password you can' => 'Si vous oubliez votre mot de passe vous pouvez',
    'Image' => 'Image',
    'Login' => 'Connexion',
    'Logout' => 'Deconnexion',
    'Message' => 'Message',
    'Notifications' => 'Notifications',
    'Password' => 'Mot de passe',
    'Please choose your new password:' => 'Veuillez entrer votre nouveau mot de passe :',
    'Please fill out the following fields to login:' => 'Veuillez remplir les champs suivants pour vous connecter :',
    'Please fill out the following fields to signup:' => 'Veuillez remplir les champs suivants pour vous enregistrer',
    'Please fill out your email. A link to reset password will be sent there.' => 'Veuillez rentrer votre email. Un lien pour changer votre mot de passe vous sera envoye.',
    'Post' => 'Post',
    'Posts' => 'Posts',
    'Request password reset' => 'Requete de changement de mot de passe',
    'Reset password' => 'Changement de mot de passe',
    'Save' => 'Enregistrer',
    'Send' => 'Envoyer',
    'Signup' => 'S\'enregistrer',
    'Title' => 'Titre',
    'Update' => 'Modifier',
    'Update Comment' => 'Modification du commentaire',
    'Update Post' => 'Modification du post',
    'Username' => 'Nom de connexion',
    'reset it' => 'le changer',
];
